language: node_js
node_js:
  - 4.1
env:
  global:
    ## node-gyp under node 4.x requires newer version of C++ compiler
    - CXX=g++-4.8
    ##
    ## Prevent 'GitHub rate limit reached' error
    ## https://gist.github.com/topheman/25241e48a1b4f91ec6d4
    - secure: ASbzd8ow6GL8Mc7RjTW6n2wa4EjlNdx0faYzHKA7P+x0UrJsbNeUJXplRHFbM9xI78ouT5B/6npdopvBCQ9d1X22vtIHmkAtNeeMN2TxVhokHJJnfExVn9IoWgiaoyJRAl0/cHmLuIjmP3KDIfZGlqCKebxDst85CceWGI5FAHY=
    ##
## node-gyp under node 4.x requires newer version of C++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
##
before_install:
  ## Enable Chrome support for KarmaJS
  ## http://stackoverflow.com/a/25661593/633438
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  ##
  - npm install -g gulp
  - npm install -g jspm
  ## Prevent 'GitHub rate limit reached' error
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  ##
before_script:
  - jspm install